using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Radium.Changeling.Components;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Radium.Changeling.UI;

[GenerateTypedNameReferences]
public sealed partial class ChangelingStorage : FancyWindow
{
    [Dependency] private readonly EntityManager _entityManager = default!;

    public EntityUid Uid;
    private ChangelingStorageBoundUserInterface _bui;
    private Dictionary<int, KeyValuePair<int, string>> IdentitiesOrder = new();
    private int _selectedIdentityServerIndex;

    public ChangelingStorage(ChangelingStorageBoundUserInterface bui, EntityUid entityUid)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ConfirmTransformation.Disabled = true;

        Uid = entityUid;
        _bui = bui;

        Resizable = false;

        IdentitiesList.SelectMode = ItemList.ItemListSelectMode.Single;
        UpdateIdentities(entityUid);

        Title = $"{Loc.GetString("changeling-transform-window-title")} ({IdentitiesList.Count}/7)";

        IdentitiesList.OnItemSelected += OnItemSelected;
        ConfirmTransformation.OnPressed += OnTransformationConfirmed;
    }

    private void OnTransformationConfirmed(BaseButton.ButtonEventArgs args)
    {
        _bui.ConfirmTransformation(_entityManager.GetNetEntity(Uid), _selectedIdentityServerIndex);
    }

    private void OnItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (!IdentitiesOrder.TryGetValue(args.ItemIndex, out var identity))
            _selectedIdentityServerIndex = identity.Key;
        ConfirmTransformation.Disabled = false;
    }

    public void UpdateIdentities(EntityUid entityUid)
    {
        IdentitiesList.Clear();
        IdentitiesOrder.Clear();

        if (!_entityManager.TryGetComponent<ChangelingComponent>(entityUid, out var changeling))
            return;

        var index = 0;
        foreach (var identity in changeling.ClientIdentitiesList)
        {
            IdentitiesList.AddItem($"{identity.Value}");
            IdentitiesOrder.Add(index, identity);
            index++;
        }
    }
}
